name: First pipeline file
steps:
  - label: "1st Job: Script building"
    command: "script.sh $$SERVER"
    env:
      SERVER: "server-a"
    agents:
      tag: "abhi"

  - label: "2nd Job: Checking agent"
    command: echo "First agent" 
    agents:
      hostname: "instance-1"

  - label: "3rd Job: Checking agent"
    command: echo "2nd agent"
    agents:
      tag: "instance-2"
 
