name: First pipeline file
agents:
  queue: default
steps:
  - label: "1st Job: Pyttest Testing "
    command: |
      pip install -r ./test/requirements.txt
      pytest -v ./test/test_algo.py
    branches: "test-analytics"
    agents:
      stage: "deploy"

