name: Test pipeline file
agents:
  stage: deploy
steps:
  - label: Image Building
    command: |
      docker build -t myos:latest .      
  - label: Docker runing
    command: |
      docker run -dit --name os1 -p 80:80 myos:latest
      docker ps
  - command: curl http://localhost
    label: runing localhost
    agents:
      stage: deploy
