name: Test pipeline file

steps:
  - command: |
      echo " Welcome to my page!" > index.html
      curl localhost
    branches: test
    plugins:
      - docker#v3.2.0:
          image: "nginx:latest"
          workdir: /usr/share/nginx/html
    agents:
      stage: deploy

 
